### PR TITLE
multitopic chat

### PR DESCRIPTION
**Pull request by shiraeeshi**
This is a simplistic implementation of multiple chatrooms: no new pages, no persistence.
Users are able to create new topics and subscribe to them, newly joined user cannot see the chat history.

### CODE REVIEW

**Comment by sergiuszkierat** [comment]
@shiraeeshi thanks for you PR. Imo, I have some general comments.
1. please update [index.html](https://github.com/JAVEO/clustered-chat/blob/master/tutorial/index.html#L83)
2. I don't see whether I am or not subscribed
3. If I send a message without a subscription to the topic, nothing is happened

**Comment by shiraeeshi** [comment]
Added current topic name to the page, and also "active" class to the selected topic.
Disabled chat-related inputs at start.
Updated index.html.

**Comment by shiraeeshi** [comment]
I want to know your opinion on the following: 
1) I think that the current version of the tutorial (without all the commits in this page) is perfect as a mini-tutorial in the activator, it's enough to understand the main concepts. I think that this multitopic  thing (my implementation of it) is not really necessary to understand the basic principles of the DistributedPubSub. I just saw an open issue and decided to implement it just for fun.
I think it's better to keep this example in its current simplistic state, and just give a link to another repo (with enhancements) in the tutorial.
2) A really important addition would be a persistence, fetching old topics and messages. I've read something about [Distributed Data](http://doc.akka.io/docs/akka/2.4.1/scala/distributed-data.html) project. Or is there another better way to implement persistence for this chat?

**Comment by shiraeeshi** [comment]
Note: my english is not very well, but I hope that my explanations in [index.html](https://github.com/JAVEO/clustered-chat/commit/a9e9117ab48ad11048375bfce98251f478c12fa6) are clear.

**Comment by sergiuszkierat** [comment]
Your PR looks good to me.
@MarcinBurczak? @wojciechk?

**Comment by MarcinBurczak** [comment]
+1

**Comment by sergiuszkierat** [comment]
1. Persistance - I haven't used a Distributed Data yet. It is an appropriate case to use it.
2. Generally, I prefer a tutorial as simple as it could be. On the other hand, it is worth to have as many use cases as possible introduced by the tutorial. Maybe, we can tag a current version and mention it within the tutorial.

**Comment by shiraeeshi** [comment]
Now the chat is more persistent: new user can fetch topics list and a chat history.

**Comment by shiraeeshi** [comment]
I haven't updated index.html, because there is a lot of changes to perform on it and I'm not good at writing texts.

**Pull request merged**
